services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./app:/usr/src/app
    user: fastapi
    restart: unless-stopped

  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres-data:
